package jcheckers.client.io.boards;

import jcheckers.client.io.InputProtocol;
import jcheckers.common.io.JCheckersDataInputStream;

public class BoardsInputProtocol extends InputProtocol {

	public static final int RATING_TOO_HIGH = 0x50;
	public static final int PACHISI_GAME_STATE = 0x8a;
	public static final int DRAUGHTS_AND_CHESS_GAME_STATE = 0x8b;
	public static final int PLAYER_SUGGESTED_PAUSE_GAME = 0xa3; // string name,
																// int id, int
																// time
	public static final int PLAYER_REJECTED_PAUSE_GAME = 0xa7; // string name,
																// int id
	public static final int PLAYER_OFFERED_DRAW = 0xb4; // string name, int id
	public static final int PLAYER_REJECTED_DRAW = 0xb7; // string name, int id
	public static final int PLAYER_ACCEPTED_DRAW = 0xb8; // string name, int id
	public static final int PLAYER_SUGGESTED_UNDO_MOVE = 0xba; // string name,
																// int id
	public static final int PLAYER_REJECTED_UNDO_MOVE = 0xbd; // string name,
																// int id
	public static final int PLAYER_ACCEPTED_UNDO_MOVE = 0xbe; // string name,
																// int id
	public static final int HIDE_CONTROLS = 0xc3;
	public static final int GAME_PAUSED = 0xc5;
	public static final int WINNERS = 0xc8;
	public static final int RATING_CHANGE = 0xcd;

	private static final int[] RESPONSE_OPCODES = new int[256];

	static {
		for (int i = 0; i < RESPONSE_OPCODES.length; i++)
			RESPONSE_OPCODES[i] = i;

		RESPONSE_OPCODES[0x08] = MY_ID;
		RESPONSE_OPCODES[0x0a] = JOIN_USER;
		RESPONSE_OPCODES[0x0c] = LEAVE_USER;
		RESPONSE_OPCODES[0x0d] = USER_LIST;
		RESPONSE_OPCODES[0x0f] = ROOM_LIST;
		RESPONSE_OPCODES[0x10] = ROOM_CHANGED;
		RESPONSE_OPCODES[0x11] = INVALID_ROOM;
		RESPONSE_OPCODES[0x13] = RESPONSE_CHAT;
		RESPONSE_OPCODES[0x14] = RESPONSE_PRIVATE_CHAT;
		RESPONSE_OPCODES[0x15] = RESPONSE_ADMIN_CHAT;
		RESPONSE_OPCODES[0x16] = PING_CONNECTION;
		RESPONSE_OPCODES[0x18] = PING;
		RESPONSE_OPCODES[0x19] = PONG;
		RESPONSE_OPCODES[0x1b] = TABLE_FOCUS;
		RESPONSE_OPCODES[0x21] = CHANGE_CRYPT_MODE;
		RESPONSE_OPCODES[0x24] = NO_CRYPT_NEXT_BLOCK;
		RESPONSE_OPCODES[0x26] = NOTIFY_BANNED_AND_DISCONNECT;
		RESPONSE_OPCODES[0x27] = NOTIFY_BANNED_ONLY;
		RESPONSE_OPCODES[0x2c] = RESPONSE_SERVER_VERSION;
		RESPONSE_OPCODES[0x2e] = SERVER_DEBUG_MESSAGE;
		RESPONSE_OPCODES[0x32] = ACCESS_EXPIRED_ON;
		RESPONSE_OPCODES[0x3a] = ACCOUNT_BLOCKED;
		RESPONSE_OPCODES[0x3d] = ACCESS_EXPIRED;
		RESPONSE_OPCODES[0x3e] = BONUS_EXPIRED;
		RESPONSE_OPCODES[0x43] = GUESTS_NOT_ALLOWED_TO_PLAY;
		RESPONSE_OPCODES[0x44] = GUESTS_NOT_ALLOWED_TO_PLAY_2;
		RESPONSE_OPCODES[0x45] = GUESTS_NOT_ALLOWED_TO_PLAY_3;
		RESPONSE_OPCODES[0x46] = BONUS_RECEIVED;
		RESPONSE_OPCODES[0x47] = BONUS_EXPIRED_2;
		RESPONSE_OPCODES[0x49] = SERVER_SHUTTING_DOWN;
		RESPONSE_OPCODES[0x4a] = INVALID_PASSWORD;
		RESPONSE_OPCODES[0x4b] = COULD_NOT_CONNECT_TO_THE_ROOM;
		RESPONSE_OPCODES[0x4c] = TABLE_NOT_EXIST;
		RESPONSE_OPCODES[0x4d] = YOU_HAVE_MAXIMUM_TABLES_OPEN;
		RESPONSE_OPCODES[0x4e] = CONNECT_TO_THE_TABLE_REFUSED;
		RESPONSE_OPCODES[0x4f] = ALREADY_CONNECTED_ON_THE_TABLE;
		RESPONSE_OPCODES[0x50] = PRIVATE_TABLE;
		RESPONSE_OPCODES[0x51] = NOT_ENOUGH_RATING;
		RESPONSE_OPCODES[0x52] = RATING_TOO_HIGH;
		RESPONSE_OPCODES[0x53] = WATCHERS_NOT_ALLOWED;
		RESPONSE_OPCODES[0x54] = NO_VACANCY_IN_THE_TABLE;
		RESPONSE_OPCODES[0x55] = COULD_NOT_CONNECT_TO_THE_TABLE_TRY_AGAIN_LATTER;
		RESPONSE_OPCODES[0x56] = COULD_NOT_CONNECT_TO_THE_TABLE;
		RESPONSE_OPCODES[0x57] = WELLCOME;
		RESPONSE_OPCODES[0x59] = RESPONSE_INFO;
		RESPONSE_OPCODES[0x5a] = PLAYER_NOT_FOUND_IN_SERVER;
		RESPONSE_OPCODES[0x5b] = UPDATE_TABLE;
		RESPONSE_OPCODES[0x5d] = AVATARS;
		RESPONSE_OPCODES[0x5e] = CLOSE_TABLE;
		RESPONSE_OPCODES[0x60] = YOURE_NOT_THE_HOST_TO_CHANGE_PARAMETERS;
		RESPONSE_OPCODES[0x61] = CONFIG_CHANGED;
		RESPONSE_OPCODES[0x63] = YOU_ARE_NOT_THE_HOST_TO_BOOT_PLAYERS;
		RESPONSE_OPCODES[0x64] = YOU_CANT_BOOT_YOURSELF;
		RESPONSE_OPCODES[0x65] = YOU_CANT_BOOT_A_PLAYER_NOT_IN_SERVER;
		RESPONSE_OPCODES[0x66] = YOU_WAS_KICKED_BY_HOST;
		RESPONSE_OPCODES[0x67] = OTHER_WAS_KICKED_BY_HOST;
		RESPONSE_OPCODES[0x68] = YOU_CANT_KICK_A_RECONNECTING_PLAYER;
		RESPONSE_OPCODES[0x6a] = YOURE_NOT_THE_HOST_TO_INVITE_PLAYERS;
		RESPONSE_OPCODES[0x6b] = YOU_CANT_INVITE_YOURSELF;
		RESPONSE_OPCODES[0x6c] = YOU_CANT_INVITE_A_PLAYER_NOT_IN_SERVER;
		RESPONSE_OPCODES[0x6d] = INVITED;
		RESPONSE_OPCODES[0x71] = INVITATION_REJECTED;
		RESPONSE_OPCODES[0x73] = INVITATION_AUTO_REJECTED;
		RESPONSE_OPCODES[0x74] = YOU_CANT_INVITE_A_PLAYER_ALREADY_IN_THE_TABLE;
		RESPONSE_OPCODES[0x75] = YOU_CANT_INVITE_A_WATCHER_DUE_NO_VACANCY;
		RESPONSE_OPCODES[0x76] = INVALID_INVIATION;
		RESPONSE_OPCODES[0x77] = INVITATION_SENT;
		RESPONSE_OPCODES[0x78] = INVITATIONS_INACTIVE;
		RESPONSE_OPCODES[0x7a] = YOURE_NOT_THE_HOST_TO_TRANSFER_HOST;
		RESPONSE_OPCODES[0x7b] = YOU_CANT_TRANSFER_HOST_TO_YOURSELF;
		RESPONSE_OPCODES[0x7c] = YOU_CANT_TRANSFER_HOST_TO_A_PLAYER_NOT_IN_SERVER;
		RESPONSE_OPCODES[0x7d] = YOU_RECEIVED_THE_HOST;
		RESPONSE_OPCODES[0x7e] = OTHER_RECEIVED_THE_HOST;
		RESPONSE_OPCODES[0x7f] = YOU_CANT_TRANSFER_THE_HOST_TO_A_RECONNECTING_PLAYER;
		RESPONSE_OPCODES[0x80] = COULD_RECONNECT_TO_THE_TABLE_TRY_AGAIN_LATTER;
		RESPONSE_OPCODES[0x81] = YOU_RECEIVED_THE_HOST_FROM_THE_SERVER;
		RESPONSE_OPCODES[0x82] = PLAYER_CONNECT;
		RESPONSE_OPCODES[0x83] = PLAYER_DISCONNECT;
		RESPONSE_OPCODES[0x84] = PLAYER_RECONNECTING;
		RESPONSE_OPCODES[0x85] = PLAYER_RECONNECTING_FAILED;
		RESPONSE_OPCODES[0x87] = YOU_CANT_WATCH_THIS_GAME;
		RESPONSE_OPCODES[0x89] = DRAUGHTS_AND_CHESS_GAME_STATE;
		RESPONSE_OPCODES[0x8d] = UPDATE_USERS;
		RESPONSE_OPCODES[0x8f] = YOU_WAS_KICKED_BY_ADMIN;
		RESPONSE_OPCODES[0x90] = OTHER_WAS_KICKED_BY_ADMIN;
		RESPONSE_OPCODES[0x92] = NO_ENOUGH_PLAYERS_TO_START_THE_GAME;
		RESPONSE_OPCODES[0x93] = START_GAME_SUGGESTED;
		RESPONSE_OPCODES[0x95] = START_GAME_SUGGEST_ACCEPTED;
		RESPONSE_OPCODES[0x96] = START_GAME_SUGGEST_REJECTED;
		RESPONSE_OPCODES[0x99] = STOP_GAME_SUGGESTED;
		RESPONSE_OPCODES[0x9c] = STOP_GAME_SUGGEST_REJECTED;
		RESPONSE_OPCODES[0xa6] = PLAYER_REJECTED_PAUSE_GAME;
		RESPONSE_OPCODES[0xc1] = QUESTION_BITS;
		RESPONSE_OPCODES[0xc2] = QUESTION_CANCELED;
		RESPONSE_OPCODES[0xc4] = STOP_GAME;
		RESPONSE_OPCODES[0xc6] = START_GAME;
		RESPONSE_OPCODES[0xca] = PLAYER_STAND_UP;
		RESPONSE_OPCODES[0xcb] = CONTINUE_GAME;
		RESPONSE_OPCODES[0xcc] = SAME_LOCAL_NETWORK;
		RESPONSE_OPCODES[0xce] = YOU_CANT_CHANGE_CONFIG_NOW;
	}

	public BoardsInputProtocol(JCheckersDataInputStream input) {
		super(input);

		opcodes = RESPONSE_OPCODES;
	}

}
